[phases.setup]
nixPkgs = ["python311", "nodejs-20_x", "postgresql"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput --clear",
  "python manage.py migrate --noinput"
]

[start]
cmd = "gunicorn Bar_project.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"

[variables]
DJANGO_SETTINGS_MODULE = "Bar_project.settings"
PYTHONPATH = "/app"