[phases.setup]
nixPkgs = ["python311"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "python manage.py migrate && gunicorn bar_website.wsgi:application --bind 0.0.0.0:$PORT --log-file -"
