[phases.setup]
nixPkgs = ["python39", "nodejs-18_x"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[phases.start]
cmd = "gunicorn Bar_project.wsgi:application --bind 0.0.0.0:$PORT"
